let tool = "https://i.imgur.com/LFuPbmG.png";
let lab = "https://i.imgur.com/VP2HfTC.png";
let stock = "https://i.imgur.com/5gKzj9A.png";

export const skills = [
  {
    type: "Languages",
    subtype: "Markup Language",
    skill: "HTML5",
    img: "https://i.imgur.com/xMMSqAc.png",
    priority: "main",
  },
  {
    type: "Languages",
    subtype: "Programming Language",
    skill: "Typescript",
    img: "https://i.imgur.com/HPlbDDQ.png",
    priority: "alternative",
  },
  {
    type: "Languages",
    subtype: "Programming Language",
    skill: "Java",
    img: "https://i.imgur.com/YJjKbt4.png",
    priority: "alternative",
  },
  {
    type: "Languages",
    subtype: "Styling Language",
    skill: "CSS3",
    img: "https://i.imgur.com/jTNhsgg.png",
    priority: "main",
  },
  {
    type: "Languages",
    subtype: "Styling Framework",
    skill: "Tailwind",
    img: "https://i.imgur.com/0Q0d39h.png",
    priority: "main",
  },
  {
    type: "Languages",
    subtype: "Styling Language",
    skill: "SCSS",
    img: "https://i.imgur.com/jkKieiK.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Styling Framework",
    skill: "Materialize",
    img: "https://i.imgur.com/kLtV7aP.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Styling Framework",
    skill: "Material UI",
    img: "https://i.imgur.com/nQneTU6.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Styling Language",
    skill: "Bootstrap",
    img: "https://i.imgur.com/NsKingN.png",
    priority: "main",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "Angular",
    img: "https://i.imgur.com/yldqsTl.jpg",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "SpringBoot",
    img: "https://i.imgur.com/fozEzEY.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "jQuery",
    img: "https://i.imgur.com/dltSXkL.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "React",
    img: "https://i.imgur.com/I9A7c4b.png",
    priority: "main",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "Redux",
    img: "https://i.imgur.com/B5jiJo7.png",
    priority: "useful",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "MobX",
    img: "https://i.imgur.com/B5jiJo7.png",
    priority: "useful",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "Node.js",
    img: "https://i.imgur.com/SqYTp68.png",
    priority: "main",
  },
  {
    type: "Languages",
    subtype: "Programming Language",
    skill: "JavaScript",
    img: "https://i.imgur.com/ckfbsq5.png",
    priority: "main",
  },
  {
    type: "Languages",
    subtype: "Programming Language",
    skill: "SQL",
    img: "https://i.imgur.com/7ImtZip.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Database",
    skill: "MongoDB",
    img: "https://i.imgur.com/a0RoQoD.png",
    priority: "main",
  },
  {
    type: "Technologies",
    subtype: "Library",
    skill: "Mongoose",
    img: "https://i.imgur.com/BPb25o6.png",
    priority: "main",
  },
  {
    type: "Technologies",
    subtype: "Database",
    skill: "PostgreSQL",
    img: "https://i.imgur.com/kqTfCNX.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Cloud Platform",
    skill: "Heroku",
    img: "https://i.imgur.com/TQ5qUGp.png",
    priority: "essential",
  },
  {
    type: "Technologies",
    subtype: "Cloud Platform",
    skill: "Vercel",
    img: "https://i.imgur.com/TQ5qUGp.png",
    priority: "essential",
  },
  {
    type: "Technologies",
    subtype: "Version Control Software",
    skill: "Git",
    img: "https://i.imgur.com/P6KIeEm.png",
    priority: "essential",
  },
  {
    type: "Technologies",
    subtype: "Database",
    skill: "AWS S3",
    img: "https://i.imgur.com/n3fTnNv.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "Django",
    img: "https://i.imgur.com/CTDcDh6.png",
    priority: "alternative",
  },
  {
    type: "Languages",
    subtype: "Programming Language",
    skill: "Python",
    img: "https://i.imgur.com/ofIVvdH.png",
    priority: "alternative",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "Express",
    img: "https://i.imgur.com/awaqvUm.png",
    priority: "main",
  },
  {
    type: "Technologies",
    subtype: "Framework",
    skill: "Next",
    img: "https://i.imgur.com/awaqvUm.png",
    priority: "main",
  },
  {
    type: "Technologies",
    subtype: "Library",
    skill: "Socket.io",
    img: "https://i.imgur.com/oCCYHpS.png",
    priority: "useful",
  },
  {
    type: "Technologies",
    subtype: "Library",
    skill: "Stripe.io",
    img: "https://i.imgur.com/oCCYHpS.png",
    priority: "useful",
  },
];

export const projects = [
  {
    name: "E-Commerce Store",
    img: "https://i.imgur.com/o0iFlPj.png",
    pages: [
      "https://i.imgur.com/o0iFlPj.png",
      "https://i.imgur.com/nO3lRwS.png",
      "https://i.imgur.com/MXacxPq.png",
      "https://i.imgur.com/GxaoMBd.png",
      "https://i.imgur.com/7Wq8OMz.png",
    ],
    summary:
      "This is a test e-commerce website that uses Typescript and Angular. Stripe was integrated to process payments. Users can view and filter through a catalogue of products from Fakestore API, add and update their cart of purchases, and process payments.",

    responsibilities: [
      "Handled client-side scripting using Angular components.",
      "Populated pages using Fakestore API.",
      "Styled pages using Tailwind to create responsive UI/UX.",
      "Integrated Stripe to process payments.",
      "Configure server for post requests to Stripe API.",
    ],
    repo: "https://github.com/tungolra/angular-ts-ecommerce-example",
    site: "[offline]",
    skills: ["Tailwind", "Angular", "Typescript", "Node.js", "HTML5"],
    type: "preview",
  },
  {
    name: "Movie Matters",
    img: "https://i.imgur.com/RjWIyoh.png",
    pages: [
      "https://i.imgur.com/RjWIyoh.png",
      "https://i.imgur.com/JSc7139.png",
      "https://i.imgur.com/BqtcDx6.png",
    ],
    summary:
      "Movie Matters is a movie review web application where users can view the latest movies and watch their trailers. Users can input reviews for each movie.",
    responsibilities: [
      "Frontend Development with React",
      "Backend Development with Spring Boot and Java",
    ],
    repo: "https://github.com/tungolra/spring-react-movies",
    site: "[offline]",
    skills: [
      "HTML5",
      "CSS3",
      "Material UI",
      "Bootstrap",
      "MongoDB",
      "SpringBoot",
      "React",
      "Java",
      "Node.js",
      "Javascript",
      "Maven",
    ],
    type: "preview",
  },
  {
    name: "Wealthy-Mi",
    img: "https://i.imgur.com/SWCYvDG.gif",
    pages: ["https://i.imgur.com/SWCYvDG.gif"],
    summary:
      "Wealthy Mi is a personal finance application created as development exercise for using a modern MERN-stack (MongoDB, ExpressJS, React, NodeJS) and implementing Agile workflow practices. Users can manage their assets and expenses, create financial goals, and forecast when they can achieve them through their dashboard with our data visualization tools.",
    responsibilities: [
      "Server and database configuration using Mongoose and MongoDB.",
      "Build out RESTful APIs and associated CRUD functions using NodeJS.",
      "Set up Redux store and slicers to make client-side API calls to retrieve user data.",
      "Utilized JSON Web Token (JWT) authorization to validate user credentials.",
      "Contribute to frontend development of UI/UX features using Bootstrap, CSS/SCSS for a responsive, modern web page.",
      "Collaborated to create sensible Agile workflows, weekly SCRUMs, and architect a CI/CD pipeline managed using Git/GitHub.",
    ],
    repo: "https://github.com/tungolra/wealthy-mi",
    site: "https://wealthy-mi.herokuapp.com/",
    skills: [
      "HTML5",
      "CSS3",
      "SCSS",
      "Bootstrap",
      "MongoDB",
      "Express",
      "React",
      "Redux",
      "Node.js",
      "Javascript",
    ],
    type: "project",
  },
  {
    name: "Chatter[Box]",
    img: "https://i.imgur.com/rnFmcto.gif",
    pages: [
      "https://i.imgur.com/tn2KTog.gif",
      "https://i.imgur.com/aXjkvsn.png",
      "https://i.imgur.com/Y0UKqRK.png",
      "https://i.imgur.com/GMz55U4.png",
    ],
    summary:
      "An instant messaging single-page application that features real-time communication between users. Developed using MongoDB, ExpressJS, ReactJS, and NodeJS (MERN) by our team of 4 developers. Taking a mobile-first approach, we utilized HTML, JSX, CSS, and Material UI to create a modern and user-friendly UI/UX.",
    responsibilities: [
      "As project lead, I organized team tasks using a Notion board, established and managed CI/CD pipeline using Github.",
      "Connected websockets using Socket.io and established routing and CRUD function to make API calls to MongoDB.",
      "Decided on schema design and data entity relationships for Mongoose models.",
      "Utilized JSON Web Token (JWT) authorization to validate user credentials.",
      "Handled client-side scripting using React hooks and API calls to populate browser views.",
      "Deployed site to Heroku.",
    ],
    repo: "https://github.com/tungolra/mern-project",
    site: "https://chatterbox-sei-55.herokuapp.com/",
    skills: [
      "HTML5",
      "CSS3",
      "Material UI",
      "Socket.io",
      "MongoDB",
      "Express",
      "React",
      "Node.js",
      "Javascript",
      "AWS S3",
    ],
    type: "project",
  },
  {
    name: "StudySmart",
    img: "https://i.imgur.com/7zzCl4k.gif",
    pages: [
      "https://i.imgur.com/qlTOdFG.png",
      "https://i.imgur.com/gYS7ySQ.png",
      "https://i.imgur.com/XyFQc7I.png",
      "https://i.imgur.com/eFMEuMT.png",
      "https://i.imgur.com/PHEGXl1.png",
      "https://i.imgur.com/FjwcwzV.png",
      "https://i.imgur.com/oPXKffZ.png",
      "https://i.imgur.com/C0WK9S1.png",
    ],
    summary:
      "An automated flashcard system to provide an online study tool that leverages the power of spaced repetition learning. A personal favourite that combines my interest in game-based learning and programming. Users can create collections of flashcards that automates the intervals for which a card is to be reviewed. Individually developed using MongoDB, ExpressJS, and NodeJS. Taking a mobile-first approach, I utilized HTML and CSS to create a simple and intuitive UI/UX.",
    responsibilities: [
      "Established routing and CRUD functions to make API calls to MongoDB.",
      "Utilized Google OAuth 2.0 to validate user credentials.",
      "Handled client-side scripting to manipulate DOM using Vanilla JavaScript and make API calls to server.",
      "Styled webpage using HTML and CSS.",
      "Configured database and server.",
      "Deployed site to Heroku",
    ],
    repo: "https://github.com/tungolra/StudySmart",
    site: "[offline]",
    skills: ["MongoDB", "Javascript", "Express", "HTML5", "CSS3", "Node.js"],
    type: "project",
  },
  {
    name: "Othello",
    img: "https://i.imgur.com/FEbqK0L.gif",
    pages: ["https://i.imgur.com/FEbqK0L.gif"],
    summary:
      "Othello, AKA Reversi, is a multiplayer, strategy board game where players aim to have the most pieces on the board before it is filled. My app features a random-bot that single-player users can play against. Developed using Vanilla JavaScript, this independent project showcases DOM manipulation, functional programming, modularization, and complex game logic. Utilized HTML and pure CSS to style a modern-classic UI/UX.",
    responsibilities: [
      "Established client-side scripting for all event listeners, event handlers, dynamically creating HTML elements, and functional game logic.",
      "Styled webpage using HTML and pure CSS to create a responsive webpage.",
      "Deployed site to GitHub pages",
    ],
    repo: "https://github.com/tungolra/Othello-js-app",
    site: "https://tungolra.github.io/Othello-js-app/",
    skills: ["Javascript", "CSS3", "HTML5"],
    type: "project",
  },
];

export const featured = [];
projects.map((project) => {
  if (project.type === "project") {
    featured.push(project);
  }
  return featured;
});
export const preview = projects.filter((project) => project.type === "preview");

export const education = [
  {
    school: "University of Toronto",
    subj: "Anthropology",
    date: "Apr 2023",
    img: "https://i.imgur.com/gr5FNay.png",
  },
  {
    school: "SkillUp by Simplilearn",
    subj: "Getting started with DevOps",
    date: "Dec 2022",
    img: "https://i.imgur.com/WMHr9HP.jpg",
  },
  {
    school: "General Assembly",
    subj: "Software Engineering Immersive",
    date: "Dec 2022",
    img: "https://i.imgur.com/BGc1dXK.png",
  },
  {
    school: "Investment Funds Institute of Canada",
    subj: "Canadian Investment Funds Operations",
    date: "Mar 2014",
    img: "https://i.imgur.com/gAHjwfc.png",
  },
  {
    school: "Sheridan College",
    subj: "Exercise Science",
    date: "Apr 2013",
    img: "https://i.imgur.com/V0hxU8s.png",
  },
];
